version: '2.3'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: elasticsearch
    network_mode: internal_apps
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    build:
      context: ./kibana
    container_name: kibana
    network_mode: internal_apps
    ports:
      - 5601:5601
    links:
      - elasticsearch

  logstash:
    build:
      context: ./logstash
    container_name: logstash
    network_mode: internal_apps
    volumes:
      - ./logstash/volumes:/usr/share/logstash/data
    ports:
      - 8080:8080
      - 8090:8090/udp
      - 8070:8070/udp
      - 12201:12201
    links:
      - elasticsearch