version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
      
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.0
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 8090:8090/tcp
      - 8091:8091/udp
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
